// Code generated by Kitex v0.9.1. DO NOT EDIT.

package security

import (
	common "clicky.website/clicky/security/kitex_gen/common"
	security "clicky.website/clicky/security/kitex_gen/security"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Code2Session(ctx context.Context, req *security.Code2SessionReq, callOptions ...callopt.Option) (r *security.Code2SessionResp, err error)
	Demo(ctx context.Context, req *common.EmptyResp, callOptions ...callopt.Option) (r *common.EmptyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSecurityClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSecurityClient struct {
	*kClient
}

func (p *kSecurityClient) Code2Session(ctx context.Context, req *security.Code2SessionReq, callOptions ...callopt.Option) (r *security.Code2SessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Code2Session(ctx, req)
}

func (p *kSecurityClient) Demo(ctx context.Context, req *common.EmptyResp, callOptions ...callopt.Option) (r *common.EmptyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Demo(ctx, req)
}
